export default {
  menu: {
    task: "Task",
    history: "History",
    config: {
      settings: "Settings",
      general: "General Config",
      llm: "LLM Config",
      theme: "Theme Config"
    }
  },
  user: "User",
  switchModel: "Switch Model",
  step: "Step",
  promptInputPlaceHolder: "Please Input Task Prompt",
  clearCacheSuccess: "Clear cache success",
  openManusAgiTips: "The above content is generated by OpenManus for reference only",
  taskStatus: {
    name: "Task Status",
    success: "Success",
    failed: "Failed",
    running: "Running",
    terminated: "Terminated",
  }
}
